### ISSUE TITLE
newIsArray - incorrect implementation

### ISSUE THREAD

**Issue by ananotherdeveloper** [udaya38/Array_methods_polyfills#1]
![image](https://user-images.githubusercontent.com/42308823/158073398-9ae777e9-90e5-426b-8af4-4f89b170556f.png)

**Comment by udaya38** [comment]
@ananotherdeveloper Thanks for the finding this issue. Have updated the code. Thanks!

Array.newIsArray=function(arr){
    return Object.prototype.toString.call(arr) === '[object Array]';
}

const arr=[1,2,3,4,5,6,7,8];
console.log(Array.newIsArray(arr));  //true
